#!/usr/bin/env bash

version=$(curl -sX GET "https://api.github.com/repos/iqlusioninc/tmkms/tags" | jq --raw-output '.[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1 | sed 's/^v//')
printf "%s" "${version}"