name: Schedule build docker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' 

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_REGISTRY_REPO: ${{ secrets.GHCR_REPO }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      
      - name: Get repository name
        id: get_repo_name
        run: |
          result=$(echo "$GITHUB_REPOSITORY" | awk -F'/' '{print $2}')
          echo "repo_name=$result" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3
    
      - name: Configure Docker
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ secrets.CI_BOT_USERNAME }}
          password: ${{ secrets.CI_BOT_TOKEN }}

      - name: Build-Push 
        run: |
          for container in $(find ./containers -mindepth 1 -maxdepth 1 -type d -printf '%f\n'); do
            upstream_version=$(./containers/$container/VERSION)
            current_version=$(curl -sL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.CI_BOT_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/user/packages/container/$container/versions | jq -r '.[] | select(.metadata.container.tags | length > 0) | .metadata.container.tags[]' | sort -V | tail -n1)
            if [ "$upstream_version" != "$current_version" ]; then
              echo "[+] New version for $container found: $upstream_version"
              platform=$(cat ./containers/$container/PLATFORM)
              docker buildx build --push --platform $platform -t ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REGISTRY_REPO }}/$container:$upstream_version ./containers/$container
            else
              echo "$container is up to date version: $current_version"
            fi
          done
