name: Build Docker Images
on:
  pull_request:
    paths:
      - "containers/**"

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_REGISTRY_REPO: ${{ secrets.GHCR_REPO }}

jobs:
  discover-modified-containers:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.modified-containers.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 2

      - name: Get list of modified container directories
        id: modified-containers
        run: |
          modified_containers=$(git diff --name-only HEAD~1 HEAD -- "containers/" | awk -F'/' '{print $2}' | sort | uniq)
          echo "modified_containers=$modified_containers"
          if [ -z "$modified_containers" ]; then
            echo "No changes detected in containers."
            matrix='{[]}'
          else
            matrix=$(jq -nc --arg containers "$modified_containers" '$containers | split("\n")')
          fi
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build-test:
    needs: discover-modified-containers
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        container: ${{ fromJson(needs.discover-modified-containers.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      
      - name: Get repository name
        id: get_repo_name
        run: |
          result=$(echo "$GITHUB_REPOSITORY" | awk -F'/' '{print $2}')
          echo "repo_name=$result" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3
    
      - name: Configure Docker
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ secrets.CI_BOT_USERNAME }}
          password: ${{ secrets.CI_BOT_TOKEN }}

      - name: Build-Push image
        continue-on-error: true
        run: |
          version=$(./containers/${{ matrix.container }}/VERSION)
          docker buildx build --platform linux/arm64,linux/amd64 -t ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REGISTRY_REPO }}/${{ steps.get_repo_name.outputs.repo_name }}/${{ matrix.container }}:latest -t ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REGISTRY_REPO }}/${{ steps.get_repo_name.outputs.repo_name }}/${{ matrix.container }}:$version ./containers/${{ matrix.container }}