name: Build and Push Docker Images
on:
  push:
    branches:
      - main
    paths:
      - "containers/**"

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_REGISTRY_REPO: ${{ secrets.GHCR_REPO }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get repository name
        id: get_repo_name
        run: |
          result=$(echo "$GITHUB_REPOSITORY" | awk -F'/' '{print $2}')
          echo "repo_name=$result" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Configure Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ secrets.CI_BOT_USERNAME }}
          password: ${{ secrets.CI_BOT_TOKEN }}

      - name: Get list of container directories
        id: containers
        run: |
          echo "::set-output name=directories::$(find ./containers -mindepth 1 -maxdepth 1 -type d -printf '%f\n')"

      - name: Build and push Docker images
        id: docker_build
        run: |
          for container in ${{ steps.containers.outputs.directories }}; do
            version=$(./containers/$container/VERSION)
            docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REGISTRY_REPO }}/${{ steps.get_repo_name.outputs.repo_name }}/$container:latest -t ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REGISTRY_REPO }}/${{ steps.get_repo_name.outputs.repo_name }}/$container:$version ./containers/$container --push
          done
